import { filterPosts } from "../../src/client/filterPosts"
import { GetSubredditResponse } from "../../src"
import { hasMoreThanNComments } from "../../src"
import { hasMoreThanNUpvoteRatio } from "../../src"
import { hasMoreThanNCrossposts } from "../../src"

test("Should keep only posts with upvote ration > 0.95", async () => {
    const result = filterPosts(fivePostsFromNews as unknown as GetSubredditResponse, [hasMoreThanNUpvoteRatio(0.95)])

    expect(result.data.children.length).toEqual(2)
})

test("Should keep only posts more than 100 comments AND more than 2 crossposts", async () => {
    const result = filterPosts(fivePostsFromNews as unknown as GetSubredditResponse, [
        hasMoreThanNComments(100),
        hasMoreThanNCrossposts(2),
    ])

    expect(result.data.children.length).toEqual(2)
})

const fivePostsFromNews = {
    kind: "Listing",
    data: {
        after: "t3_ub4a74",
        dist: 5,
        modhash: "",
        geo_filter: null,
        children: [
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "news",
                    selftext: "",
                    author_fullname: "t2_dvc31gw7",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Macron beats Le Pen in French election – projections - BBC News",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/news",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_ub0ffn",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.94,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 22678,
                    total_awards_received: 7,
                    media_embed: {},
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 22678,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1650823341.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "bbc.co.uk",
                    allow_live_comments: true,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://www.bbc.co.uk/news/live/world-europe-61151604?ns_mchannel=social&amp;ns_source=twitter&amp;ns_campaign=bbc_live&amp;ns_linkname=62658d4b6b7942142fe95887%26Polls%20close%20in%20France%262022-04-24T18%3A00%3A07.598Z&amp;ns_fee=0&amp;pinned_post_locator=urn:asset:15950671-e4c6-41eb-8dd2-0962e69f328d&amp;pinned_post_asset_id=62658d4b6b7942142fe95887&amp;pinned_post_type=share",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: false,
                    pinned: false,
                    over_18: false,
                    all_awardings: [
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 150,
                            id: "award_f44611f1-b89e-46dc-97fe-892280b13b82",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 2048,
                            static_icon_width: 2048,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "Thank you stranger. Shows the award.",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 2,
                            static_icon_height: 2048,
                            name: "Helpful",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: null,
                            icon_height: 2048,
                            penny_price: null,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                        },
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 125,
                            id: "award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 2048,
                            static_icon_width: 2048,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "When you come across a feel-good thing.",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 4,
                            static_icon_height: 2048,
                            name: "Wholesome",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: null,
                            icon_height: 2048,
                            penny_price: null,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                        },
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 20,
                            id: "award_abb865cf-620b-4219-8777-3658cf9091fb",
                            penny_donate: null,
                            award_sub_type: "PREMIUM",
                            coin_reward: 0,
                            icon_url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_512.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_16.png",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_32.png",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_48.png",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_64.png",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/Starstruck_128.png",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 512,
                            static_icon_width: 512,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "Can't stop seeing stars",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 1,
                            static_icon_height: 512,
                            name: "Starstruck",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png?width=16&amp;height=16&amp;auto=webp&amp;s=800ea0775a3f25602bfab03058d64d25352c04d2",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png?width=32&amp;height=32&amp;auto=webp&amp;s=1d4be9117f8e389c54e0a7e23918355d7d2df185",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png?width=48&amp;height=48&amp;auto=webp&amp;s=45443e65acd1cf76585f7c9d904e1484f89db521",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png?width=64&amp;height=64&amp;auto=webp&amp;s=f4164f96ab1df25de2024b8b65e9ce91d3424c86",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png?width=128&amp;height=128&amp;auto=webp&amp;s=b09819f49e26e5ad518dbdf1aa69f0916d514c6e",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: "APNG",
                            icon_height: 512,
                            penny_price: 0,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/snotiq9vxyn51_Starstruck.png",
                        },
                    ],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qh3l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "ub0ffn",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "Astroblemes",
                    discussion_type: null,
                    num_comments: 958,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/news/comments/ub0ffn/macron_beats_le_pen_in_french_election/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.bbc.co.uk/news/live/world-europe-61151604?ns_mchannel=social&amp;ns_source=twitter&amp;ns_campaign=bbc_live&amp;ns_linkname=62658d4b6b7942142fe95887%26Polls%20close%20in%20France%262022-04-24T18%3A00%3A07.598Z&amp;ns_fee=0&amp;pinned_post_locator=urn:asset:15950671-e4c6-41eb-8dd2-0962e69f328d&amp;pinned_post_asset_id=62658d4b6b7942142fe95887&amp;pinned_post_type=share",
                    subreddit_subscribers: 24554968,
                    created_utc: 1650823341.0,
                    num_crossposts: 0,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "news",
                    selftext: "",
                    author_fullname: "t2_8hkvlhy8",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Philadelphia toddler dies after being shot at drugs deal",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/news",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_uavawe",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.91,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 19794,
                    total_awards_received: 5,
                    media_embed: {},
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 19794,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: true,
                    thumbnail: "",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1650808580.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "news.sky.com",
                    allow_live_comments: true,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://news.sky.com/story/philadelphia-toddler-shot-dead-after-dad-used-him-as-a-human-shield-in-a-drug-deal-12597795",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: false,
                    pinned: false,
                    over_18: false,
                    all_awardings: [
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 150,
                            id: "award_f44611f1-b89e-46dc-97fe-892280b13b82",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 2048,
                            static_icon_width: 2048,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "Thank you stranger. Shows the award.",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 1,
                            static_icon_height: 2048,
                            name: "Helpful",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&amp;height=16&amp;auto=webp&amp;s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&amp;height=32&amp;auto=webp&amp;s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&amp;height=48&amp;auto=webp&amp;s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&amp;height=64&amp;auto=webp&amp;s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&amp;height=128&amp;auto=webp&amp;s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: null,
                            icon_height: 2048,
                            penny_price: null,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                        },
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 125,
                            id: "award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 2048,
                            static_icon_width: 2048,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "When you come across a feel-good thing.",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 3,
                            static_icon_height: 2048,
                            name: "Wholesome",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&amp;height=16&amp;auto=webp&amp;s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&amp;height=32&amp;auto=webp&amp;s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&amp;height=48&amp;auto=webp&amp;s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&amp;height=64&amp;auto=webp&amp;s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&amp;height=128&amp;auto=webp&amp;s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: null,
                            icon_height: 2048,
                            penny_price: null,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                        },
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 100,
                            id: "award_81cf5c92-8500-498c-9c94-3e4034cece0a",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://i.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=16&amp;height=16&amp;auto=webp&amp;s=5ef2e0d3bc325a7e1fb2d22c1fec1e6b4b6fc745",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=32&amp;height=32&amp;auto=webp&amp;s=4932a768430215109c262c88950bcba46e9e1b23",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=48&amp;height=48&amp;auto=webp&amp;s=287f90bae451c50dfa5076e5e70c30f7396421b2",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=64&amp;height=64&amp;auto=webp&amp;s=4313a1836086f33447b60d11d3d16cf2c57d20de",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=128&amp;height=128&amp;auto=webp&amp;s=b32edce435e22d111c10cdebeefd2e49ece8b6e4",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 2048,
                            static_icon_width: 2048,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "Staring into the abyss and it's staring right back",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 1,
                            static_icon_height: 2048,
                            name: "Dread",
                            resized_static_icons: [
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=16&amp;height=16&amp;auto=webp&amp;s=5ef2e0d3bc325a7e1fb2d22c1fec1e6b4b6fc745",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=32&amp;height=32&amp;auto=webp&amp;s=4932a768430215109c262c88950bcba46e9e1b23",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=48&amp;height=48&amp;auto=webp&amp;s=287f90bae451c50dfa5076e5e70c30f7396421b2",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=64&amp;height=64&amp;auto=webp&amp;s=4313a1836086f33447b60d11d3d16cf2c57d20de",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://preview.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png?width=128&amp;height=128&amp;auto=webp&amp;s=b32edce435e22d111c10cdebeefd2e49ece8b6e4",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: "PNG",
                            icon_height: 2048,
                            penny_price: 0,
                            award_type: "global",
                            static_icon_url: "https://i.redd.it/award_images/t5_22cerq/nvfe4gyawnf51_Dread.png",
                        },
                    ],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qh3l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "uavawe",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "EX-Machinaa",
                    discussion_type: null,
                    num_comments: 1692,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/news/comments/uavawe/philadelphia_toddler_dies_after_being_shot_at/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://news.sky.com/story/philadelphia-toddler-shot-dead-after-dad-used-him-as-a-human-shield-in-a-drug-deal-12597795",
                    subreddit_subscribers: 24554968,
                    created_utc: 1650808580.0,
                    num_crossposts: 6,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "news",
                    selftext: "",
                    author_fullname: "t2_avobu",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "‘Unusual’ deep-sea jellyfish discovered off California coast",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/news",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_uaslwd",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.97,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 5516,
                    total_awards_received: 0,
                    media_embed: {},
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 5516,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: true,
                    thumbnail: "",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1650799131.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "theguardian.com",
                    allow_live_comments: true,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://www.theguardian.com/environment/2022/apr/22/unusual-jellyfish-discovered-california-atolla-reynoldsi",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: false,
                    pinned: false,
                    over_18: false,
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qh3l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "uaslwd",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "zsreport",
                    discussion_type: null,
                    num_comments: 207,
                    send_replies: false,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/news/comments/uaslwd/unusual_deepsea_jellyfish_discovered_off/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.theguardian.com/environment/2022/apr/22/unusual-jellyfish-discovered-california-atolla-reynoldsi",
                    subreddit_subscribers: 24554968,
                    created_utc: 1650799131.0,
                    num_crossposts: 1,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "news",
                    selftext: "",
                    author_fullname: "t2_3du8a5l",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Multiple people shot outside Atlanta Waffle House",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/news",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    top_awarded_type: null,
                    hide_score: false,
                    name: "t3_uaxlb4",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.94,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 1801,
                    total_awards_received: 1,
                    media_embed: {},
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 1801,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {
                        gid_1: 1,
                    },
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1650815242.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "newschannel9.com",
                    allow_live_comments: true,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://newschannel9.com/news/local/multiple-shot-outside-atlanta-waffle-house",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: false,
                    pinned: false,
                    over_18: false,
                    all_awardings: [
                        {
                            giver_coin_reward: null,
                            subreddit_id: null,
                            is_new: false,
                            days_of_drip_extension: null,
                            coin_price: 100,
                            id: "gid_1",
                            penny_donate: null,
                            award_sub_type: "GLOBAL",
                            coin_reward: 0,
                            icon_url: "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
                            days_of_premium: null,
                            tiers_by_required_awardings: null,
                            resized_icons: [
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_width: 512,
                            static_icon_width: 512,
                            start_date: null,
                            is_enabled: true,
                            awardings_required_to_grant_benefits: null,
                            description: "Shows the Silver Award... and that's it.",
                            end_date: null,
                            subreddit_coin_reward: 0,
                            count: 1,
                            static_icon_height: 512,
                            name: "Silver",
                            resized_static_icons: [
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                                    width: 16,
                                    height: 16,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                                    width: 32,
                                    height: 32,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                                    width: 48,
                                    height: 48,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                                    width: 64,
                                    height: 64,
                                },
                                {
                                    url: "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                                    width: 128,
                                    height: 128,
                                },
                            ],
                            icon_format: null,
                            icon_height: 512,
                            penny_price: null,
                            award_type: "global",
                            static_icon_url: "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
                        },
                    ],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qh3l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "uaxlb4",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "dfssfggg",
                    discussion_type: null,
                    num_comments: 550,
                    send_replies: true,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/news/comments/uaxlb4/multiple_people_shot_outside_atlanta_waffle_house/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://newschannel9.com/news/local/multiple-shot-outside-atlanta-waffle-house",
                    subreddit_subscribers: 24554968,
                    created_utc: 1650815242.0,
                    num_crossposts: 3,
                    media: null,
                    is_video: false,
                },
            },
            {
                kind: "t3",
                data: {
                    approved_at_utc: null,
                    subreddit: "news",
                    selftext: "",
                    author_fullname: "t2_aunip1k5",
                    saved: false,
                    mod_reason_title: null,
                    gilded: 0,
                    clicked: false,
                    title: "Texas BBQ chain owed employees nearly $900,000",
                    link_flair_richtext: [],
                    subreddit_name_prefixed: "r/news",
                    hidden: false,
                    pwls: 6,
                    link_flair_css_class: null,
                    downs: 0,
                    top_awarded_type: null,
                    hide_score: true,
                    name: "t3_ub4a74",
                    quarantine: false,
                    link_flair_text_color: "dark",
                    upvote_ratio: 0.98,
                    author_flair_background_color: null,
                    subreddit_type: "public",
                    ups: 588,
                    total_awards_received: 0,
                    media_embed: {},
                    author_flair_template_id: null,
                    is_original_content: false,
                    user_reports: [],
                    secure_media: null,
                    is_reddit_media_domain: false,
                    is_meta: false,
                    category: null,
                    secure_media_embed: {},
                    link_flair_text: null,
                    can_mod_post: false,
                    score: 588,
                    approved_by: null,
                    is_created_from_ads_ui: false,
                    author_premium: false,
                    thumbnail: "",
                    edited: false,
                    author_flair_css_class: null,
                    author_flair_richtext: [],
                    gildings: {},
                    content_categories: null,
                    is_self: false,
                    mod_note: null,
                    created: 1650834218.0,
                    link_flair_type: "text",
                    wls: 6,
                    removed_by_category: null,
                    banned_by: null,
                    author_flair_type: "text",
                    domain: "kiro7.com",
                    allow_live_comments: true,
                    selftext_html: null,
                    likes: null,
                    suggested_sort: null,
                    banned_at_utc: null,
                    url_overridden_by_dest:
                        "https://www.kiro7.com/news/trending/texas-bbq-chain-owed-employees-nearly-900000/4ZO7QXTMNZHRHC4WODPMEKTXNU/",
                    view_count: null,
                    archived: false,
                    no_follow: false,
                    is_crosspostable: false,
                    pinned: false,
                    over_18: false,
                    all_awardings: [],
                    awarders: [],
                    media_only: false,
                    can_gild: false,
                    spoiler: false,
                    locked: false,
                    author_flair_text: null,
                    treatment_tags: [],
                    visited: false,
                    removed_by: null,
                    num_reports: null,
                    distinguished: null,
                    subreddit_id: "t5_2qh3l",
                    author_is_blocked: false,
                    mod_reason_by: null,
                    removal_reason: null,
                    link_flair_background_color: "",
                    id: "ub4a74",
                    is_robot_indexable: true,
                    report_reasons: null,
                    author: "suppersready90",
                    discussion_type: null,
                    num_comments: 64,
                    send_replies: false,
                    whitelist_status: "all_ads",
                    contest_mode: false,
                    mod_reports: [],
                    author_patreon_flair: false,
                    author_flair_text_color: null,
                    permalink: "/r/news/comments/ub4a74/texas_bbq_chain_owed_employees_nearly_900000/",
                    parent_whitelist_status: "all_ads",
                    stickied: false,
                    url: "https://www.kiro7.com/news/trending/texas-bbq-chain-owed-employees-nearly-900000/4ZO7QXTMNZHRHC4WODPMEKTXNU/",
                    subreddit_subscribers: 24554968,
                    created_utc: 1650834218.0,
                    num_crossposts: 2,
                    media: null,
                    is_video: false,
                },
            },
        ],
        before: null,
    },
}
